### ISSUE TITLE
ERROR - Billing Detail over 12 months report

### ISSUE THREAD

**Issue by dtoczala** [dtoczala/IBM_Cloud_Admin#3]
Peter Tuton has seen this error:

Building current ANNUAL billing details by org (in JSON) 

Traceback (most recent call last):
  File "IBM_Cloud_Admin.py", line 1903, in <module>
    main_menu()
  File "IBM_Cloud_Admin.py", line 1124, in main_menu
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1164, in show_default
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1850, in back
    menu_actions['main_menu']()
  File "IBM_Cloud_Admin.py", line 1124, in main_menu
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1133, in exec_menu
    menu_actions['main_menu']()
  File "IBM_Cloud_Admin.py", line 1124, in main_menu
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1194, in bx_account_orgs
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1850, in back
    menu_actions['main_menu']()
  File "IBM_Cloud_Admin.py", line 1124, in main_menu
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1326, in show_billing_summary_json
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1850, in back
    menu_actions['main_menu']()
  File "IBM_Cloud_Admin.py", line 1124, in main_menu
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1463, in show_billing_detail_json
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1850, in back
    menu_actions['main_menu']()
  File "IBM_Cloud_Admin.py", line 1124, in main_menu
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1632, in show_annual_billing_summary_json
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1850, in back
    menu_actions['main_menu']()
  File "IBM_Cloud_Admin.py", line 1124, in main_menu
    exec_menu(choice)
  File "IBM_Cloud_Admin.py", line 1136, in exec_menu
    menu_actions[ch]()
  File "IBM_Cloud_Admin.py", line 1523, in show_annual_billing_detail_json
    jsonout = json.loads(errout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Log contains:

ERROR (ExecCmd_Output) - on call -> bx billing org-usage tuton@au1.ibm.com -d 2018-01 -r all --json
ERROR (ExecCmd_Output) - on call -> bx billing org-usage tuton@au1.ibm.com -d 2018-01 -r all --json
                      error code ->  
                      returned   ->

**Comment by dtoczala** [comment]
This may be related to Issue #1 - I m trying to reproduce the issue

**Comment by dtoczala** [comment]
Fix needed for return on non-JSON content (i.e. some ERROR message).  
Fix put in on June 19, 2018 by Tox
